project:
  type: website
  output-dir: docs

website:
  title: "Diego Gomes"
  favicon: "images/mondrian_icon.png"
  
  page-footer: 
    center: |
      [Contact me](mailto:diego.gomes.data@gmail.com)
    left: |
      Made with [Quarto](https://quarto.org/)
    right: |
      [Githib Code Repo](https://github.com/gomes-diego)
    background: "#F8F5F0"
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd
     # - text: Blog
     #   href: custom_projects.qmd
    right:
      # - about.qmd
      - icon: github
        href: https://github.com/gomes-diego
      - icon: linkedin
        href: https://linkedin.com
      - icon: envelope
        href: mailto:diego.gomes.data@gmail.com
    background: "#F8F5F0"
format:
  html:
    theme: 
      light: sandbox
      # dark: [sandbox, theme_dark_custom.scss]
    highlight-style: arrow
    code-link: true
    code-fold: show
    code-summary: "Show the code"
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    css: styles.css

editor: visual

